require 'socket'

require_relative './protocol/protocol_cobs'
require_relative './protocol/protocol_crc'
require_relative './protocol/protocol_packet'
require_relative './protocol/protocol_type'
require_relative './parse/parse_type'
require_relative './parse/parse_wiremap'
require_relative './engine/engine_do'
require_relative './engine/engine_transport'
